server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 42.103.147.82
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 42.103.147.82
leyou:
  sms:
    accessKeyId: ATAI5tM6Tfna571igCvCboAB # 你自己的accessKeyId
    accessKeySecret: vAoKAdAylPJWmk7xKh55C9rLYezNAo # 你自己的AccessKeySecret
    signName: 阿里云短信测试 # 签名名称
    verifyCodeTemplate: SMS_154950909 # 模板名称
